# Generated by Django 4.2.7 on 2026-02-15 02:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Session ID = user_id để nhóm các tin nhắn",
                        max_length=255,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI")],
                        help_text="Vai trò: human hoặc ai",
                        max_length=10,
                    ),
                ),
                ("content", models.TextField(help_text="Nội dung tin nhắn")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, help_text="Thời gian tạo tin nhắn"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        help_text="Người dùng sở hữu tin nhắn",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="chat_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Chat Message",
                "verbose_name_plural": "Chat Messages",
                "db_table": "chat_messages",
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["session_id", "created_at"],
                        name="chat_messag_session_597c4e_idx",
                    )
                ],
            },
        ),
    ]
