# Generated by Django 4.2.7 on 2026-01-19 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("ebooks", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("deposit", "Nạp tiền"), ("purchase", "Mua sách")],
                        max_length=20,
                    ),
                ),
                ("amount", models.IntegerField(help_text="+ khi nạp, - khi mua")),
                ("description", models.CharField(max_length=500)),
                (
                    "balance_after",
                    models.PositiveIntegerField(help_text="Số dư sau giao dịch"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ebook",
                    models.ForeignKey(
                        blank=True,
                        help_text="Chỉ có khi type='purchase'",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="ebooks.ebook",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Giao dịch",
                "verbose_name_plural": "Giao dịch",
                "db_table": "transactions",
                "ordering": ["-created_at"],
            },
        ),
    ]
