# Generated by Django 6.0.1 on 2026-03-15 03:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0011_alter_ebook_category'),
        ('transactions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnedEbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchased_price', models.PositiveIntegerField()),
                ('purchased_at', models.DateTimeField(auto_now_add=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_by', to='ebooks.ebook')),
                ('transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owned_ebook', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_ebooks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sách đã mua',
                'verbose_name_plural': 'Sách đã mua',
                'db_table': 'owned_ebooks',
                'ordering': ['-purchased_at'],
                'constraints': [models.UniqueConstraint(fields=('user', 'ebook'), name='unique_user_owned_ebook')],
            },
        ),
    ]
