# Generated by Django 4.2.7 on 2026-01-19 17:05

from django.db import migrations, models
import django.db.models.deletion
import pgvector.django


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("bio", models.TextField(blank=True)),
                ("image", models.ImageField(blank=True, upload_to="authors/")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Tác giả",
                "verbose_name_plural": "Tác giả",
                "db_table": "authors",
            },
        ),
        migrations.CreateModel(
            name="Ebook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                ("description", models.TextField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("fiction", "Tiểu thuyết"),
                            ("science", "Khoa học"),
                            ("business", "Kinh doanh"),
                            ("self_help", "Phát triển bản thân"),
                            ("technology", "Công nghệ"),
                            ("history", "Lịch sử"),
                            ("children", "Thiếu nhi"),
                            ("other", "Khác"),
                        ],
                        max_length=50,
                    ),
                ),
                ("price", models.PositiveIntegerField(help_text="Giá bằng Coins")),
                ("file_url", models.FileField(upload_to="ebooks/")),
                ("cover_image", models.ImageField(upload_to="covers/")),
                (
                    "embedding",
                    pgvector.django.VectorField(blank=True, dimensions=1536, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ebooks",
                        to="ebooks.author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Ebook",
                "verbose_name_plural": "Ebooks",
                "db_table": "ebooks",
                "ordering": ["-created_at"],
            },
        ),
    ]
