# Generated by Django 4.2.7 on 2026-01-19 17:29

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebook",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=768, null=True),
        ),
    ]
