# Generated by Django 4.2.7 on 2026-02-13 17:02

from django.db import migrations
import pgvector.django


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0002_alter_ebook_embedding"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ebook",
            name="embedding",
            field=pgvector.django.VectorField(blank=True, dimensions=3072, null=True),
        ),
    ]
