# Generated by Django 4.2.7 on 2026-02-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0003_alter_ebook_embedding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Thể loại",
                "verbose_name_plural": "Thể loại",
                "db_table": "categories",
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="ebook",
            name="category",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
