# Generated by Django 6.0.1 on 2026-03-02 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0004_category_alter_ebook_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebook',
            name='file_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ebook',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
