# Generated by Django 6.0.1 on 2026-03-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0005_ebook_file_mime_alter_ebook_file_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ebook',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='ebook',
            name='cover_mime',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='ebook',
            name='cover_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
