# Generated by Django X.Y on 2026-03-03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ebooks", "0006_remove_ebook_cover_image_ebook_cover_mime_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ebook",
            name="category_fk",
            field=models.ForeignKey(
                to="ebooks.category",
                on_delete=django.db.models.deletion.SET_NULL,
                null=True,
                blank=True,
                related_name="ebooks_fk",
            ),
        ),
    ]