# Generated by Django 6.0.1 on 2026-03-15 05:28

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ebooks', '0011_alter_ebook_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EbookReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('content', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ebook', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='ebooks.ebook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ebook_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ebook_reviews',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='EbookReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reviews/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='ebooks.ebookreview')),
            ],
            options={
                'db_table': 'ebook_review_images',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='ebookreview',
            constraint=models.UniqueConstraint(fields=('ebook', 'user'), name='unique_user_review_per_ebook'),
        ),
    ]
